name: arke_dart
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  nyxx: ^6.6.1
  dotenv: ^4.2.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
